name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This is a issue PR. If there isn't any activity this issue may be closed. Thanks for contributing to 1host"
        stale-pr-message: "This is a stale PR. If there isn't any activity this issue may be closed. Thanks for contributing to 1host"
        stale-issue-label: "status: stale" # todo: update this
        stale-pr-label: "status: stale" # todo: update this
