on: [push, pull_request]
name: Build, Test and maybe Publish
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - uses: actions/setup-node@v1
      name: nodejs
      with:
        node-version: 16.x
    - uses: mikeal/merge-release@master
      name: releasse
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/setup-node@v2
      name: nodejs again
      with:
        node-version: 16.x
        registry-url: 'https://npm.pkg.github.com'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
